MD003:
  # Heading style
  style: "atx"

MD004:
  # List style
  style: "dash"

MD013:
  # 'Disable' the line length
  line_length: 800

MD033:
  # The only way to do superscript is with 'sup'
  allowed_elements:
    - sup

MD046:
  # Block style
  style: "fenced"

MD048:
  # Code fence style
  style: "backtick"

MD049:
  # Emphasis style
  style: "underscore"

MD050:
  # Strong style
  style: "asterisk"

MD055:
  # Table pipe style
  style: "leading_and_trailing"
