remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

domain: "pwhittlesea.github.io"
url: "https://pwhittlesea.github.io"
baseurl: "/"

title: Phillip Whittlesea-Clark
description: >-
  A flume ride through my conciousness.

author:
  name: Phillip Whittlesea-Clark
  email: "pw.github@thega.me.uk"

minima:
  skin: solarized
  header_pages:
    - about.md
    - cv.md
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    - platform: github
      user_url: "https://github.com/pwhittlesea"
    - platform: x
      user_url: "https://twitter.com/pwhittlesea"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/phillipwhittlesea/"
    - platform: goodreads
      user_url: "https://www.goodreads.com/user/show/163685297-phillip"
  show_excerpts: true
