remote_theme: mmistakes/minimal-mistakes@4.25.1
date_format: "%Y-%m-%d %H:%M"

show_excerpts: true

minimal_mistakes_skin: "default"

# Site Settings
locale: "en-GB"
title: "thega.me.uk"
title_separator: "-"
subtitle: "Useless content on unimportant topics"
name: "Phillip Whittlesea-Clark"
description: "Personal blog of Phillip Whittlesea-Clark"
url: "https://thega.me.uk"
baseurl: "/"
domain: "thega.me.uk"
repository: "pwhittlesea/pwhittlesea.github.io"
masthead_title: "thega.me.uk"
enable_copy_code_button: true
teaser: /assets/images/teaser_default.png

copyright: "Phillip Whittlesea-Clark - All Rights Reserved"
copyright_url: "https://thega.me.uk"

# Site Author
author:
  name: "Phillip Whittlesea-Clark"
  avatar: "/assets/images/profile_pic.png"
  bio: "Software Architect & Dungeon Master"
  location: "Southampton"
  email: "pw.github@thega.me.uk"
  links: &follow
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/thega.me.uk"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@pwhittlesea"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pwhittlesea"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/phillipwhittlesea/"
    - label: "The StoryGraph"
      icon: "fas fa-fw fa-book"
      url: "https://app.thestorygraph.com/profile/gingerphill"

# Set all the footer links to those in the author block
footer:
  links: *follow

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true
      read_time: true
      show_date: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
      author_profile: true

# Process relative links
relative_links:
  enabled: true
  collections: true

# Jekyll Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
